# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f6a8893b476f1d09747cfaeeb1f1f926d5d2ea1325e86cce6a059f03c780dda21d2aacd259febf416709e79c81c72e5c6e975802df586bac555a2552cc5b202

test:
  secret_key_base: 783b44a86f618aa6b56b943197362974c96d2a7b7f35068ab8bcbbf348c86077c4e333029994125a114ff90a533bbc7d21293e2e36844ecf7a1f4fdad11f5781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
